# -*- coding: utf-8 -*-
"""lotto number generator.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rZZaXzbwJexvfn1pWuzq02BOngxIKR1H
"""

import numpy as np
from numpy.random import default_rng

n = 6
rng = default_rng()
lotto = rng.choice(range(60), size = n, replace=False)

lotto